-- Create a dedicated schema (optional, you can stay in SYSTEM if you prefer)
-- CREATE USER accountdb IDENTIFIED BY accountdb_password;
-- GRANT CONNECT, RESOURCE TO accountdb;

-- Switch to the schema (skip if staying in SYSTEM)
-- ALTER SESSION SET CURRENT_SCHEMA = accountdb;

-- Drop table if it already exists (optional cleanup)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE expenses';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create the expenses table
CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year NUMBER(4) NOT NULL,
    month VARCHAR2(20) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    amount NUMBER(10,2) NOT NULL
);

-- Insert sample data for 2026
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Jan', 'Food & Beverages', 450);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Jan', 'Entertainment', 100);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Mac', 'Food & Beverages', 600);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Mac', 'Entertainment', 130);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Apr', 'Transport', 200);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Apr', 'Utilities', 300);

-- Commit changes
COMMIT;
