-- Drop table if it already exists
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE expenses';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create the expenses table
CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year NUMBER(4) NOT NULL,
    month NUMBER(2) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    amount NUMBER(10,2) NOT NULL
);

-- Insert sample data for 2026 - January
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Food & Beverages', 450);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Entertainment', 100);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Leisure & Sports', 80);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Services', 300);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Shopping', 200);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Telecom', 50);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 1, 'Utilities', 80);

-- Insert sample data for 2026 - February
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Food & Beverages', 390);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Entertainment', 80);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Leisure & Sports', 70);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Services', 250);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Shopping', 450);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Telecom', 50);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 2, 'Utilities', 70);

-- Insert sample data for 2026 - March
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Food & Beverages', 600);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Entertainment', 130);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Leisure & Sports', 180);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Services', 200);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Shopping', 150);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Telecom', 60);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 3, 'Utilities', 70);

-- Insert sample data for 2026 - April
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Food & Beverages', 480);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Entertainment', 110);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Leisure & Sports', 95);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Services', 280);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Shopping', 320);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Telecom', 55);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 4, 'Utilities', 85);

-- Insert sample data for 2026 - May
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Food & Beverages', 520);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Entertainment', 120);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Leisure & Sports', 100);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Services', 290);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Shopping', 280);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Telecom', 50);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 5, 'Utilities', 90);

-- Insert sample data for 2026 - June
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Food & Beverages', 410);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Entertainment', 95);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Leisure & Sports', 120);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Services', 260);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Shopping', 380);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Telecom', 55);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 6, 'Utilities', 75);

-- Insert sample data for 2026 - July
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Food & Beverages', 550);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Entertainment', 140);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Leisure & Sports', 110);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Services', 310);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Shopping', 240);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Telecom', 60);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 7, 'Utilities', 100);

-- Insert sample data for 2026 - August
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Food & Beverages', 470);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Entertainment', 105);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Leisure & Sports', 85);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Services', 275);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Shopping', 360);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Telecom', 50);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 8, 'Utilities', 80);

-- Insert sample data for 2026 - September
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Food & Beverages', 510);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Entertainment', 125);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Leisure & Sports', 105);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Services', 295);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Shopping', 270);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Telecom', 55);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 9, 'Utilities', 95);

-- Insert sample data for 2026 - October
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Food & Beverages', 430);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Entertainment', 90);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Leisure & Sports', 75);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Services', 240);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Shopping', 400);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Telecom', 50);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 10, 'Utilities', 70);

-- Insert sample data for 2026 - November
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Food & Beverages', 560);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Entertainment', 145);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Leisure & Sports', 115);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Services', 320);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Shopping', 220);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Telecom', 65);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 11, 'Utilities', 105);

-- Insert sample data for 2026 - December
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Food & Beverages', 650);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Entertainment', 200);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Leisure & Sports', 150);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Services', 400);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Shopping', 500);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Telecom', 70);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 12, 'Utilities', 120);

-- Commit changes
COMMIT;
