-- Drop table if it already exists
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE expenses';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create the expenses table
CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year NUMBER(4) NOT NULL,
    month VARCHAR2(20) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    amount NUMBER(10,2) NOT NULL
);

-- Insert sample data for 2026
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Jan', 'Food & Beverages', 450);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Jan', 'Entertainment', 100);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Feb', 'Transport', 200);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Feb', 'Utilities', 300);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Mar', 'Food & Beverages', 600);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Mar', 'Entertainment', 130);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Apr', 'Healthcare', 250);
INSERT INTO expenses (year, month, category, amount) VALUES (2026, 'Apr', 'Transport', 180);

-- Commit changes
COMMIT;
